# Generated by Django 4.2.23 on 2025-09-13 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('Pilot', 'Pilot'), ('Engineer', 'Engineer'), ('Admin', 'Admin'), ('Medical', 'Medical'), ('Ground_Staff', 'Ground Staff')], max_length=20)),
                ('unit', models.CharField(max_length=50)),
                ('years_of_service', models.IntegerField()),
                ('age', models.IntegerField()),
                ('fitness_score', models.IntegerField()),
                ('stress_index', models.IntegerField()),
                ('missions_participated', models.IntegerField()),
                ('mission_success_rate', models.FloatField()),
                ('peer_review_score', models.IntegerField()),
                ('leadership_score', models.IntegerField()),
                ('engagement_score', models.IntegerField()),
                ('attrition_risk', models.BooleanField()),
                ('leadership_potential', models.CharField(max_length=10)),
                ('readiness_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('commander', 'Commander'), ('hr', 'HR Manager'), ('medical', 'Medical Officer'), ('training', 'Training Officer'), ('personnel', 'Personnel')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
